apiVersion: v1
kind: Pod
metadata:
  name: spring-boot
  labels:
    app: spring-boot
spec:
  containers:
    - name: spring-boot
      image: yakmandocker/spring-boot:tagVersion
      ports:
        - containerPort: 8080
  imagePullSecrets:
    - name: nodesecret